### ISSUE TITLE
Does it support the UTF-8?

### ISSUE THREAD

**Issue by qqaimh** [zacanger/koa-cookies#1]
(node:16500) UnhandledPromiseRejectionWarning: TypeError: argument value is invalid
    at new Cookie (E:\nodekoa\node_modules\cookies\index.js:125:11)
    at Cookies.set (E:\nodekoa\node_modules\cookies\index.js:88:16)
    at E:\nodekoa\node_modules\koa-cookies\index.js:17:17
    at login (E:\nodekoa\controller\homeController.js:24:55)
(node:16500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zautumnz** [comment]
This library does not. Since browsers handle unicode in cookies inconsistently, the `cookies` module that Koa uses enforces `/^[\u0009\u0020-\u007e\u0080-\u00ff]+$/`. See also: https://stackoverflow.com/questions/1969232/allowed-characters-in-cookies
For that reason I didn't add any unicode handling, since it seems safer to use ASCII. If it seems like a valuable feature, I could add in `encodeURIComponent` calls, though.

**Comment by zautumnz** [comment]
Added in `koa-cookies@1.1.1`
